# Generated by Django 3.1.4 on 2020-12-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_auto_20201213_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='created_by',
            field=models.UUIDField(null=True),
        ),
    ]
