version: '3.4'

services:
  db:
    container_name: imdb_db
    image: postgres:latest
    env_file:
      - .env
    command: postgres -c listen_addresses='*'
    volumes:
      - imdb_db:/var/lib/postgresql/data/
    networks:
      - imdb_default

  web:
    container_name: imdb_service
    image: imdb_service
    build: .
    env_file:
      - .env
    expose:
      - 8000
    volumes:
      - .:/src
      - static_volume:/src/static
      - media_volume:/src/media
    networks:
      - imdb_default
    depends_on:
      - db

  nginx:
    container_name: imdb_nginx
    image: nginx:latest
    ports:
      - 8000:9000
    volumes:
      - ./config/nginx/conf.d/local.conf:/etc/nginx/conf.d/local.conf
      - static_volume:/src/static
      - media_volume:/src/media
    depends_on:
      - web
    networks:
      - imdb_default

networks:
  imdb_default:

volumes:
  static_volume:
  media_volume:
  imdb_db: